# 2-bridge knot rational number calculator
# 
# Shion Fukuzawa
# June 13, 2018

def two_bridge(l):
    """Calculates the rational number associated to the 2-bridge knot"""
    res = rec_frac(l, 0)
    return res

def rec_frac(l, i):
    """Calculates the recursive fraction generated by the list"""
    if i != len(l)-1:
        ret = l[i] + 1/rec_frac(l, i+1)
    else:
        ret = l[i]
    return ret

if __name__=="__main__":
    knot_seq = []
    while True:
        a = int(input("insert element: "))
        if a == 0:
            break
        knot_seq.append(a)
    
    a = two_bridge(knot_seq)
    print(a)