Debugger entered--Lisp error: (void-variable year)
  (= year "freshman")
  (if (= year "freshman") (1) (if (= year "sophomore") (2) (if (= year "junior") (3) (if (= year "senior") (4) (0)))))
  eval((if (= year "freshman") (1) (if (= year "sophomore") (2) (if (= year "junior") (3) (if (= year "senior") (4) (0))))) nil)
  elisp--eval-last-sexp(t)
  eval-last-sexp(t)
  eval-print-last-sexp(nil)
  funcall-interactively(eval-print-last-sexp nil)
  call-interactively(eval-print-last-sexp nil nil)
  command-execute(eval-print-last-sexp)
